// Created using: http://www.dotnetwise.com/Code/Externs/
var d3 = {
    "version": {},
    "ascending": function () {},
    "descending": function () {},
    "min": function () {},
    "max": function () {},
    "extent": function () {},
    "sum": function () {},
    "mean": function () {},
    "quantile": function () {},
    "median": function () {},
    "bisectLeft": function () {},
    "bisectRight": function () {},
    "bisect": function () {},
    "bisector": function () {},
    "shuffle": function () {},
    "permute": function () {},
    "pairs": function () {},
    "zip": function () {},
    "transpose": function () {},
    "keys": function () {},
    "values": function () {},
    "entries": function () {},
    "merge": function () {},
    "range": function () {},
    "map": function () {},
    "nest": function () {},
    "set": function () {},
    "behavior": {
        "drag": function () {},
        "zoom": function () {}
    },
    "rebind": function () {},
    "dispatch": function () {},
    "event": function () {},
    "requote": function () {},
    "selection": function () {},
    "ns": {
        "prefix": {
            "svg": {},
            "xhtml": {},
            "xlink": {},
            "xml": {},
            "xmlns": {}
        },
        "qualify": function () {}
    },
    "select": function () {},
    "selectAll": function () {},
    "mouse": function () {},
    "touches": function () {},
    "interpolateZoom": function () {},
    "hsl": function () {},
    "hcl": function () {},
    "lab": function () {},
    "rgb": function () {},
    "functor": function () {},
    "xhr": function () {},
    "dsv": function () {},
    "csv": function () {},
    "tsv": function () {},
    "touch": function () {},
    "timer": function () {},
    "round": function () {},
    "formatPrefix": function () {},
    "time": {
        "year": function () {},
        "years": function () {},
        "day": function () {},
        "days": function () {},
        "dayOfYear": function () {},
        "sunday": function () {},
        "sundays": function () {},
        "sundayOfYear": function () {},
        "monday": function () {},
        "mondays": function () {},
        "mondayOfYear": function () {},
        "tuesday": function () {},
        "tuesdays": function () {},
        "tuesdayOfYear": function () {},
        "wednesday": function () {},
        "wednesdays": function () {},
        "wednesdayOfYear": function () {},
        "thursday": function () {},
        "thursdays": function () {},
        "thursdayOfYear": function () {},
        "friday": function () {},
        "fridays": function () {},
        "fridayOfYear": function () {},
        "saturday": function () {},
        "saturdays": function () {},
        "saturdayOfYear": function () {},
        "week": function () {},
        "weeks": function () {},
        "weekOfYear": function () {},
        "format": function () {},
        "second": function () {},
        "seconds": function () {},
        "minute": function () {},
        "minutes": function () {},
        "hour": function () {},
        "hours": function () {},
        "month": function () {},
        "months": function () {},
        "scale": function () {}
    },
    "locale": function () {},
    "format": function () {},
    "geo": {
        "stream": function () {},
        "area": function () {},
        "bounds": function () {},
        "centroid": function () {},
        "clipExtent": function () {},
        "conicEqualArea": function () {},
        "albers": function () {},
        "albersUsa": function () {},
        "path": function () {},
        "transform": function () {},
        "projection": function () {},
        "projectionMutator": function () {},
        "equirectangular": function () {},
        "rotation": function () {},
        "circle": function () {},
        "distance": function () {},
        "graticule": function () {},
        "greatArc": function () {},
        "interpolate": function () {},
        "length": function () {},
        "azimuthalEqualArea": function () {},
        "azimuthalEquidistant": function () {},
        "conicConformal": function () {},
        "conicEquidistant": function () {},
        "gnomonic": function () {},
        "mercator": function () {},
        "orthographic": function () {},
        "stereographic": function () {},
        "transverseMercator": function () {}
    },
    "geom": {
        "hull": function () {},
        "polygon": function () {},
        "voronoi": function () {},
        "delaunay": function () {},
        "quadtree": function () {}
    },
    "interpolateRgb": function () {},
    "interpolateObject": function () {},
    "interpolateNumber": function () {},
    "interpolateString": function () {},
    "interpolate": function () {},
    "interpolators": {
        "0": function () {}
    },
    "interpolateArray": function () {},
    "ease": function () {},
    "interpolateHcl": function () {},
    "interpolateHsl": function () {},
    "interpolateLab": function () {},
    "interpolateRound": function () {},
    "transform": function () {},
    "interpolateTransform": function () {},
    "layout": {
        "bundle": function () {},
        "chord": function () {},
        "force": function () {},
        "hierarchy": function () {},
        "partition": function () {},
        "pie": function () {},
        "stack": function () {},
        "histogram": function () {},
        "pack": function () {},
        "tree": function () {},
        "cluster": function () {},
        "treemap": function () {}
    },
    "random": {
        "normal": function () {},
        "logNormal": function () {},
        "bates": function () {},
        "irwinHall": function () {}
    },
    "scale": {
        "linear": function () {},
        "log": function () {},
        "pow": function () {},
        "sqrt": function () {},
        "ordinal": function () {},
        "category10": function () {},
        "category20": function () {},
        "category20b": function () {},
        "category20c": function () {},
        "quantile": function () {},
        "quantize": function () {},
        "threshold": function () {},
        "identity": function () {}
    },
    "svg": {
        "arc": function () {},
        "line": function () {},
        "area": function () {},
        "chord": function () {},
        "diagonal": function () {},
        "symbol": function () {},
        "symbolTypes": {
            "0": {},
            "1": {},
            "2": {},
            "3": {},
            "4": {},
            "5": {}
        },
        "axis": function () {},
        "brush": function () {}
    },
    "transition": function () {},
    "text": function () {},
    "json": function () {},
    "html": function () {},
    "xml": function () {}
}
